/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2018-08-22 12:42:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Emprestimo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/20151074010433/Downloads/MeuDeusAjudaNesseProjeto/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProjetoBiblioteca/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1308137770000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1530713177854L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Realizar emprestimo de livros</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tbackground-image:\r\n");
      out.write("\turl(\"https://png.pngtree.com/thumb_back/fw800/back_pic/03/92/99/5257e4bc31c91a2.jpg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button{\r\n");
      out.write("width: 40%;\r\n");
      out.write("margin-left: 30%;\r\n");
      out.write("margin-right: 30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".area-header {\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tbackground-color:;\r\n");
      out.write("}\r\n");
      out.write(".icone {\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\twidth:60px;\r\n");
      out.write("\theight:60px;\r\n");
      out.write("\tmargin-left: 20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".name-proj {\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin-top:15px;\r\n");
      out.write("\tmargin-left:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer{\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbottom: 20px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("#formulario {\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("\tpadding: 3% 2%;\r\n");
      out.write("\tmargin: 2% 13%;\r\n");
      out.write("\tbackground-color: rgba(200,200,200,0.5);\r\n");
      out.write("\tborder-radius: 40px ;\r\n");
      out.write("\tpadding: 1%;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("input[type=text], label{\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\tmargin: 0% 25%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <div id=\"formulario\">\r\n");
      out.write("    <form action=\"servico\" id=\"formulario\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<h2>Relizar Emprestimo:</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<label>Livro: </label> <input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.titulo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><br/>\r\n");
      out.write("\t\t<label>Aluno (mat.): </label> <input type=\"text\" name=\"aluno\" maxlength=\"14\" /><br/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"livro\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idLivro }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"comandos\" value=\"EmprestarLivro\">\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<button type=\"submit\">Confirmar Emprestimo</button>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"busca\">\r\n");
      out.write("\t\t<h2>Buscar emprestimos:</h2>\r\n");
      out.write("\t\t<form action=\"servico\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"emprestimos\" placeholder=\"Emprestimo...\">\r\n");
      out.write("\t\t\t<input type = \"hidden\" value=\"BuscaEmprestimo\">\r\n");
      out.write("\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"servico\">\r\n");
      out.write("    \t\t<input type = \"hidden\" name=\"comandos\" value=\"BuscaEmprestimo\">\r\n");
      out.write("    \t\t<button type=\"submit\" >Listar emprestimos</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
